### ISSUE TITLE
Onkyo 1.2.7 not working on raspberry pi 3

### ISSUE THREAD

**Issue by toshibochan** [miracle2k/onkyo-eiscp#100]
Onkyo 1.0 is working normal but Onkyo 1.2.5 not working on raspberry pi.
any one have same issue?

**Comment by toshibochan** [comment]
on Mac 1.2.5 is working okay but not on PI.

**Comment by toshibochan** [comment]
Is any way to download older version?

**Comment by tuctboh** [comment]
works for me...

```
pi@valhalla-p1:~ $ uname -a
Linux valhalla-p1 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
```

**Comment by toshibochan** [comment]
onkyo-eiscp 1.2.7 not working on my raspberry pi 3 and 3 plus. anyone have this problem? on raspberry pi zero and on Mac is working okay.

**Comment by toshibochan** [comment]
onkyo --discover
Nothing happens

onkyo -i 1009B0DD1D11 zone2.selector=sat
No receivers found.

**Comment by toshibochan** [comment]
if use work
onkyo --host "IP address" zone2.selector=sat
