### ISSUE TITLE
Double quotes in options

### ISSUE THREAD

**Issue by instalator** [miracle2k/onkyo-eiscp#117]
e.g. https://github.com/miracle2k/onkyo-eiscp/blob/b27e8158c09b04a2160e395d9710f6748f431bf5/eiscp-commands.yaml#L493
Is this a mistake or should it be so?

PS
https://github.com/miracle2k/onkyo-eiscp/blob/b27e8158c09b04a2160e395d9710f6748f431bf5/eiscp-commands.yaml#L795

**Comment by instalator** [comment]
https://github.com/miracle2k/onkyo-eiscp/blob/b27e8158c09b04a2160e395d9710f6748f431bf5/eiscp-commands.yaml#L795

**Comment by peskdale** [comment]
I believe these are incorrect. I'm having similar problems with [the CTL command](https://github.com/miracle2k/onkyo-eiscp/blob/master/eiscp-commands.yaml#L573). QSTN works fine, but UP/DOWN include the unicode quotes, so simply don't work when calling them using the onkyo script.

The import script [was fixed](https://github.com/miracle2k/onkyo-eiscp/commit/1ebfb086915d5726f9eedf574934e6f1ded7dace#diff-09f6f837fc27a2ed634eaad95c70721b) back in 2017 to correct this but nothing seems to have been done to fix the existing bad commands.

Calling the same commands manually using the raw method works.

**Comment by peskdale** [comment]
Actually, looking at it some more, that 'fix' in 2017 would not have actually worked. It's looking for a closing quote (201d) for both sides of the command, and so not catching anything with an opening quote (201c).
