### ISSUE TITLE
BUG: Set volume HEX encoding

### ISSUE THREAD

**Issue by reddec** [miracle2k/onkyo-eiscp#19]
**Object**:

This command will return 'N/A' state for `TX-NR809`

```
onkyo --host <host> --port <port> volume=15
```

This error reporoduces only if exists non-digit symbol in HEX representation of volume level.

**Reason:**
Incorrect volume HEX decoding on receiver. It is required only uppercase symbols.

**Decision:**
Convert volume HEX representation to upper string

**Comment by miracle2k** [comment]
I think this was fixed by this: https://github.com/miracle2k/onkyo-eiscp/commit/05ab80c24cd8cf252d451f9eedd41d1dd2aa2663

(available in master branch version).

**Comment by reddec** [comment]
Yes, you are right. After installing directly from git, the problem is gone.
