### ISSUE TITLE
Python module incompatible with Python3

### ISSUE THREAD

**Issue by miniconfig** [miracle2k/onkyo-eiscp#20]
Is there any chance you'd consider updating this to work with Python3 as well?  I'm trying to use it with a python3 project, and I fixed a couple incompatibilities, but struct.pack is throwing some errors I don't really understand, and I think this might be a bit beyond my limited python skills.

**Comment by miracle2k** [comment]
Unfortunately I won't be working on this any time soon, but if someone want to attempt it (I don't think it should be so hard), I think I can help them along.
