### ISSUE TITLE
Small doc update

### ISSUE THREAD

**Issue by fdutheil** [miracle2k/onkyo-eiscp#22]
Hi,
I successfully used this from a Linux Mint (straight-forward) and Gentoo Linux. That's awesome :)
What I observed: the code seems compatible with python 2.X only, and not python 3.X.
And I'm no python expert, so I had to dig a bit in Python & commands documentation to see how to install the code as a non-root user (in order not to install a python module outside of the official distro package manager): so I used `easy_install --user onkyo-eiscp==dev` and updated my PATH like this `export PATH="$PATH:~/.local/bin"`.

I think a mention of these 2 things ine the 'readme' doc could be useful to newcomers here. Thanks! :)

**Comment by miracle2k** [comment]
I'm not sure if this use-case is a common one. Why did you need to install it in user?

Are there distros now that only ship with Python 3? Maybe we should make it compatible.

**Comment by fdutheil** [comment]
Indeed, it may not be so frequent, I let you decide. But the need would be: not altering the OS in any way out of the use of the OS official package manager.

As for python interpreter, rolling updates distros (Gentoo, Arch) have switched to python 3 as the default interpreter (Gentoo still leaves python 2.7 available, don't know for Arch), but standard distros are coming the same route (Fedora coming out next month will default to python 3). Not debian/ubuntu though: their definition of "default python interpreter" is that everything must work with python 3, but ```python``` will remain a link to the python 2 interpreter: https://wiki.ubuntu.com/Python/3

**Comment by pll** [comment]
If you use virtualenvs for python, it's trivial to install it in user space.

**Comment by miracle2k** [comment]
In general, this kind of general purpose instruction might not belong into the docs; maybe for us it's a bit more relevant, since users might want to run an app like this this on NAS devices and the like, where a global installation could be problematic.

Nevertheless, I will close this. If someone provides a pull request for the docs that talks about this subject, I will merge it.
