### ISSUE TITLE
Little Confused, Volume commands supported?

### ISSUE THREAD

**Issue by AppleTechy** [miracle2k/onkyo-eiscp#24]
I was wondering if volume commands were currently supported as I didn't see anything saying they were but I also didn't see anything saying they weren't. If volume commands currently are supported will they be coming?

**Comment by mikerodrigues** [comment]
Volume control is supported. You can send raw MVL## commands where "##" is the volume level you want converted to hex.

You can also use:

onkyo volume:level-up
onkyo volume:level-down
onkyo volume:32               # This doesn't seem to work for me but the above methods work fine.

**Comment by szaske** [comment]
This seems bugged.  It works for any volumes above 16-100, but doesn't work for volumes 0-15.  With my receiver 1-15 is actually pretty loud, so I'm currently not able to set the volume to very low.  You can however set the volume to 16, then do 14 copies of the command level-down...but that is a pretty ugly work around.  I'll try to figure out how to use the RAW command in the meantime.

**Comment by owagner** [comment]
Tried using the development version? The release has a bug related to hex parsing of numbers.

**Comment by mikerodrigues** [comment]
@szaske I'm using version 0.9.1 via pip and it works fine: `onkyo main.volume:12`

**Comment by miracle2k** [comment]
It's fixed in the master branch. I have to do a new release at some point.

For now, install the fixed version using:

     easy_install https://github.com/miracle2k/onkyo-eiscp/archive/master.zip
