### ISSUE TITLE
Right syntax for NPU

### ISSUE THREAD

**Issue by hanssipi** [miracle2k/onkyo-eiscp#25]
Great job miracle2k!! love it!
Need some help with the NPU or net-popup-message command.
The help says:

 None - x -> Popup Display Type
 'T': Popup text is top
 'B': Popup text is bottom
 'L': Popup text is list format

aaa...aaa -> Popup Title, Massage
 when x = 'T' or 'B'
    Top Title [0x00] Popup Title [0x00] Popup Message [0x00](valiable-length Unicode letter [UTF-8 encoded])

 when x = 'L'
    Top Title [0x00] Item Title 1 [0x00] Item Parameter 1 [0x00] ... [0x00] Item Title 6 [0x00] Item Parameter 6 [0x00](valiable-length Unicode letter [UTF-8 encoded])

y -> Cursor Position on button
 '0' : Button is not Displayed
 '1' : Cursor is on the button 1
 '2' : Cursor is on the button 2

bbb...bbb -> Text of Button
    Text of Button 1 [0x00] Text of Button 2 [0x00]

But whatever i tried, i always get an error.

onkyo NPUB,"aaaa","bbbbbb",2,"ddddd"
Error: Need at least command and argument

onkyo net-popup-message:Baaaa,bbbbbb2ddddd
Error: "baaaa" is not a valid argument for command "net-popup-message" in zone "main"

Can you give me the right syntax for the command.
Thanks, hansipi

**Comment by miracle2k** [comment]
I'm closing some old questions. Some of the more complicated commands I don't have any experience with, and they may require some code to be added, or the auto-generated definition in the YAML file to be corrected. If anyone figures something out and wants to contribute it as a fix or documentation - awesome!
