### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by szaske** [miracle2k/onkyo-eiscp#30]
I found this Python library to be exactly what I was looking for.  Unfortunately it doesn't look like anyone has touched the code in a few years.  When I started experimenting with it I found some errors in the documentation.  In many places they gave the example:

`receiver.command('power on')`

This will not work.  Instead you need to use
`receiver.command('system-power on')`

Also
`receiver.command('system-power off')`

will not work, you need to instead use
`receiver.command('system-power standby')`

Hope this is helpful to anyone struggling to get this working.

**Comment by miracle2k** [comment]
This is a long standing bug. The commands as defined are generated from the onkyo documentation.

The commands mentioned in the documentation are aspirational - I wanted to define aliases to make some of them more accessible.

**Comment by miracle2k** [comment]
`receiver.command('input-selector pc')` is also broken, it seems.

**Comment by miracle2k** [comment]
Should be fixed by b17123d.
