### ISSUE TITLE
ISCP command OSDMENU fails with ValueError: Timeout waiting for response.

### ISSUE THREAD

**Issue by lnbotur** [miracle2k/onkyo-eiscp#32]
Great project! Just what I was looking for. Thanks for providing it!
I found a problem related to ISCP command OSDMENU and other OSDxxxx subcommands. Here are the details:
Environment: Onkyo TX-NR646, onkyo-eiscp running on raspberry pi 2
When running:
onkyo OSDMENU
I am getting:
<eISCP(unknown) 192.168.36.144:60128>: OSDMENU
Traceback (most recent call last):
  File "/usr/bin/onkyo", line 9, in <module>
    load_entry_point('onkyo-eiscp==0.9.1', 'console_scripts', 'onkyo')()
  File "/usr/lib/python2.7/site-packages/onkyo_eiscp-0.9.1-py2.7.egg/eiscp/script.py", line 129, in run
    sys.exit(main() or 0)
  File "/usr/lib/python2.7/site-packages/onkyo_eiscp-0.9.1-py2.7.egg/eiscp/script.py", line 122, in main
    response = receiver.raw(iscp_command)
  File "/usr/lib/python2.7/site-packages/onkyo_eiscp-0.9.1-py2.7.egg/eiscp/core.py", line 391, in raw
    return filter_for_message(self.get, iscp_message)
  File "/usr/lib/python2.7/site-packages/onkyo_eiscp-0.9.1-py2.7.egg/eiscp/core.py", line 251, in filter_for_message
    raise ValueError('Timeout waiting for response.')
ValueError: Timeout waiting for response.

In line 251 of core.py it is expected that the first three characters of the ISCP command in the request message and the response message will match. Unfortunately for OSDxxxx commands this is not the case. Attached is Whireshark trace. There the OSDMENU command is answered with NLSCP. The same happens with other OSDxxxx commands. 
In the ISCP protocol specification I couldn't find that the command in the response message shall match the one in the request message. How about modifying the source code to accept NLSCP as answer to OSDxxxx commands? 

[OSDMENU.zip](https://github.com/miracle2k/onkyo-eiscp/files/356010/OSDMENU.zip)

Thanks in advance!

**Comment by miracle2k** [comment]
I'm closing some old questions. Some of the more complicated commands I don't have any experience with, and they may require some code to be added, or the auto-generated definition in the YAML file to be corrected. If anyone figures something out and wants to contribute it as a fix or documentation - awesome!
