### ISSUE TITLE
Master volume values

### ISSUE THREAD

**Issue by jappish84** [miracle2k/onkyo-eiscp#34]
First of all I'd like to thank you for this great script, I use it daily! Hat off to you sir. 

Ok, so, running the `onkyo -n 809 master-volume=xx` command work good as long as I type a value equal or higher than 16. So volume level 16 is the lowest I can control. Any value lower than that returns as N/A on the TX-NR809

**Comment by miracle2k** [comment]
This should be fixed in the development version. I should make a new release.

**Comment by miracle2k** [comment]
I just did.
