### ISSUE TITLE
System power off not working

### ISSUE THREAD

**Issue by musician2000** [miracle2k/onkyo-eiscp#37]
Hi 

Just tried this below and got an error message? am I doing something wrong?

onkyo system-power=off
Error: "off" is not a valid argument for command "system-power" in zone "main"

**Comment by pll** [comment]
Have read the docs?

$ onkyo --help-commands main system-power
Possible values for this command:
  standby - sets System Standby
  on - sets System On
  query - gets the System Power Status

**Comment by miracle2k** [comment]
The problem here is that the README in the frontpage suggest system-power=off. My idea at the time was to provide some sensible aliases for the names that the Onkyo docs suggest.

**Comment by miracle2k** [comment]
Merging into https://github.com/miracle2k/onkyo-eiscp/issues/30.
