### ISSUE TITLE
how change input and volume?

### ISSUE THREAD

**Issue by toshibochan** [miracle2k/onkyo-eiscp#38]
how i can change MAIN or ZONE 2 input an volume?

**Comment by miracle2k** [comment]
Something like this should work:

`onkyo zone2.volume=55`

**Comment by toshibochan** [comment]
Thanks! Can I change input of zone 2? My tuner have separate zone 2 impute from main zone.

**Comment by miracle2k** [comment]
Check the eiscp-commands.yaml file in the repo for all available commands.
