### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by pll** [miracle2k/onkyo-eiscp#43]
I'm working on a home-automation project and hoping to wrap my onkyo TX-8050 into it. Unfortunately, I can't seem to figure out how to get some things to work. For example, choosing one of the pre-defined Network service channels (e.g. Pandora).  The docs say:
```
$ onkyo --help-commands main net-service
Possible values for this command:
  None - select Network Service directly
ss -> Network Service
 00:Media Server (DLNA)
 01:Favorite
 02:vTuner
 03:SIRIUS
 04:Pandora
 05:Rhapsody
 06:Last.fm
 07:Napster
 08:Slacker
 09:Mediafly
 0A:Spotify
 0B:AUPEO!
 0C:Radiko
 0D:e-onkyo

i-> Acount Info
 0: No
 1: Yes
"aaaa...aaaa": User Name ( 128 Unicode letters [UTF-8 encoded] max )
"bbbb...bbbb": Password ( 128 Unicode letters [UTF-8 encoded] max )
```
But it is unclear how this should look on the command line.  When I simply try to select the Pandora option as noted above, I get an error like this:
```
$ onkyo -n 8050 main net-service=04
Error: Need at least command and argument
```
For example, what does this mean?
```
Possible values for this command:
  None - select Network Service directly
```
Does that mean I run the command like this:
```
$ onkyo -n 8050 main net-service=None
```
I'll gladly submit PRs for correcting the docs and/or other code fixes as well.

Thanks.
--
Paul

**Comment by miracle2k** [comment]
I would happily accept PRs. The command database has been generated from Onkoy's Excel, and a lot of the commands, in particular more rare ones, might be problematic the way the generated writes them into the YAML, or the way the code handles them.

In other words, the code might not send the right command to Onkyo, or doesn't let the user select the right command via the CLI. This would need fixing individually.

**Comment by miracle2k** [comment]
I'm closing some old questions. Some of the more complicated commands I don't have any experience with, and they may require some code to be added, or the auto-generated definition in the YAML file to be corrected. If anyone figures something out and wants to contribute it as a fix or documentation - awesome!
