### ISSUE TITLE
Python 3 support.

### ISSUE THREAD

**Issue by miracle2k** [miracle2k/onkyo-eiscp#45]
There is a branch based on patch I received (https://github.com/miracle2k/onkyo-eiscp/tree/py3), but we need to support both versions in the same codebase.

**Comment by moskovskiy82** [comment]
How to install this version via the pip3?

**Comment by moskovskiy82** [comment]
Not sure but getting the following

`(homeassistant_venv) homeassistant@home:/$ pip3 install --upgrade onkyo-eiscp
Collecting onkyo-eiscp
Requirement already up-to-date: docopt>=0.4.1 in /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/docopt-0.6.2-py3.4.egg (from onkyo-eiscp)
Requirement already up-to-date: netifaces in /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/netifaces-0.10.5-py3.4-linux-armv7l.egg (from onkyo-eiscp)
Installing collected packages: onkyo-eiscp
Successfully installed onkyo-eiscp-1.0`

And than 

`(homeassistant_venv) homeassistant@home:/$ onkyo --discover
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/bin/onkyo", line 7, in <module>
from eiscp.script import run
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/eiscp/__init__.py", line 6, in <module>
from core import eISCP
ImportError: No module named 'core'`

**Comment by moskovskiy82** [comment]
pip install git+https://github.com/miracle2k/onkyo-eiscp.git@py3
this doesn't seem to help as well

**Comment by miracle2k** [comment]
Seems there is a problem with the code. I don't have the bandwidth to look at it right now, though.

**Comment by moskovskiy82** [comment]
Thank you for looking into it. As this is the last step i need to move to HA completely.

**Comment by moskovskiy82** [comment]
Ok my mistake. I've installed the onkyo-eiscp via the pip3 install.
That pulls the python2 version. 
So i have replaced everything in the eiscp dir with py3 version. That works well ecxept for the binary onkyo file.
I have tried building it with 
`python3 setup.py build`
But that generates only lib directory - no onkyo
Trying to run the 
`python3 generate_commands_module.py`
Gives the following error
```
  File "generate_commands_module.py", line 39
    except TypeError, exc:
                    ^
```

**Comment by robert-budde** [comment]
This patch fixes it
`diff --git a/eiscp/__init__.py b/eiscp/__init__.py
index 314dd86..1e723d9 100644
--- a/eiscp/__init__.py
+++ b/eiscp/__init__.py
@@ -3,4 +3,4 @@
 
 __author__ = 'Michael Elsdoerfer <michael@elsdoerfer.com>'
 
-from core import eISCP
+from .core import eISCP
diff --git a/eiscp/core.py b/eiscp/core.py
index 11c00c8..f44f53a 100644
--- a/eiscp/core.py
+++ b/eiscp/core.py
@@ -6,7 +6,7 @@ import queue, threading
 import netifaces
 from collections import namedtuple
 
-import commands
+from . import commands
 
 
 class ISCPMessage(object):`

(derived from https://github.com/qedi-r/onkyo-eiscp/commit/99383ef6110d5d9c5302a1f882645cbca92b876b)

Best regards
Robert

**Comment by woodyl** [comment]
I've tried to install eiscp into Python 3.6 using pip3.  I made the patches shown above, but now I'm getting errors when I try to use eiscp as a Python module and also when I run onkyo from bash shell.  Here's an example of an error using the command:  'onkyo power:on source:game'

`File "/usr/lib/python3.6/site-packages/eiscp/script.py", line 107, in main
    receivers = receivers[:1]
TypeError: 'dict_values' object is not subscriptable`

Looks like I'm getting Python3 compatibility issues.  Is that a problem with the code, or the way I installed it?

**Comment by robert-budde** [comment]
Sorry - in  order to make the script work you also need to do the same modifications to script.py - after that everything should work

**Comment by woodyl** [comment]
Actually, it looks like the problem is that the documentation for the Python module usage is wrong.  E.g.:
Documentation says:
receiver.command('power on')
receiver.command('source pc')
receiver.command('power', 'on', zone='main')

None of those work for me in either Python 2.7 or Python 3.6  These commands do work:
receiver.command('system-power=on')
receiver.command('system-power=standby')
receiver.command('zone2.selector=tuner')

I don't believe that I had to make any modifications to script.py to get these to work.
I would be happy to rewrite the documentation to indicate the correct module command usage and also to expand the command examples for the onkyo binary if that would be useful

**Comment by miracle2k** [comment]
I pull request would be nice, because this is a long standing problem that I was too lazy I guess to fix, but note that the reason the documentation is wrong is that I want the documentation to work as it says. I'd like to change the command definitions, the YAML file, to have these aliases. power instead of the more complicated system-power.

**Comment by moskovskiy82** [comment]
robert-budde's diff is working as a charm.

**Comment by miracle2k** [comment]
Closing as the new release should include Python 3 support.
