### ISSUE TITLE
Recursion to deep in Setup.py build

### ISSUE THREAD

**Issue by Carl-Horst** [miracle2k/onkyo-eiscp#52]
I cannot build - continuously get the error recursion to deep. Would it be possible to refactor the routine to be iterative? Python recursions are limited to a depth of 999. Thanks!

**Comment by miracle2k** [comment]
Which routine? Can you post a stack trace?

**Comment by Carl-Horst** [comment]
Unfortunately I can't reproduce it any longer. Must have been during the netifaces installation. I manually installed netifaces 0.10.4 (instead of 0.10.5) and afterwards the build/setup went fine.
