### ISSUE TITLE
onkyo-eiscp runs on the command line but not in python script

### ISSUE THREAD

**Issue by bill-orange** [miracle2k/onkyo-eiscp#53]
eiscp runs fine form the command line. I have tested it with discover, on and standby.  It seems more reliable than my phone app.

However, when I try to use in in a python script, I get:
Traceback (most recent call last):
  File "/home/pi/myprojects/Python/onkyo.py", line 1, in <module>
    import eiscp
ImportError: No module named 'eiscp'
>>> 
So logically, I tried: 

sudo pip install eiscp

and I got:

pi@raspberrypi:~ $ sudo pip install eiscp
Downloading/unpacking eiscp
  Could not find any downloads that satisfy the requirement eiscp
Cleaning up...
No distributions at all found for eiscp
Storing debug log for failure in /root/.pip/pip.log

What am I doing wrong?

I am running Raspian 3-2-17 on a PI Zero Wireless yes, I was in line at MicroCenter early).

Bill

**Comment by miracle2k** [comment]
The package name is onkyo-eiscp.

**Comment by bill-orange** [comment]
Well, that got me a little way down the path.

sudo pip install onkyo-eiscp worked fine.  When I try to run my python file I get module not found on 'import eiscp' and a syntax error on the '-' if I try 'import onkyo-eiscp'.  

What am I missing?

**Comment by bill-orange** [comment]
got It! A prior project had changed my default to python 3.

Thanks.
