### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by toshibochan** [miracle2k/onkyo-eiscp#56]
How to update the eiscp files and eiscp-commands.yaml?

**Comment by miracle2k** [comment]
The YAML file is generated from an Onkyo excel file. This process is complicated. But the idea is that manual changes and fixes can be made there.

**Comment by toshibochan** [comment]
Where this file is locate on raspberry pi?

**Comment by miracle2k** [comment]
It's not included in the installed package. It's information is written into commands.py.

**Comment by toshibochan** [comment]
how i can update manually?

**Comment by toshibochan** [comment]
i can't find command.yaml on my mac and raspberry pi

**Comment by miracle2k** [comment]
I will need more information about what you want to achieve.

**Comment by toshibochan** [comment]
I see you update some file on github, example the eiscp-commands.yaml files and others. I want install this news files on my computer but I don't know how.
