### ISSUE TITLE
error to install DEV version

### ISSUE THREAD

**Issue by toshibochan** [miracle2k/onkyo-eiscp#58]
i'm trying to install DEV version but i'm getting error:

sudo easy_install onkyo-eiscp==dev

Searching for onkyo-eiscp==dev
Reading https://pypi.python.org/simple/onkyo-eiscp/
No local packages or download links found for onkyo-eiscp==dev
error: Could not find suitable distribution for Requirement.parse('onkyo-eiscp==dev')

How i can install DEV version?

**Comment by miracle2k** [comment]
This is no longer supported by pip and I should remove the readme instructions. You should install the tarball-url from github directly.
