### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by moskovskiy82** [miracle2k/onkyo-eiscp#62]
With all the latest pull requests merged - onkyo-eiscp is working great.
The only problem there was a pull request in Home Assistant (quite popular home automation software) to use this library instead of the forked one.

So instead of a new code - we are getting the release 1.0 which contains some bugs especially with python3 compatability.
Below are the relevant lines from home-assistant.

miracle2k, is there a possiility you will put up a 1.1 Release so all the fixed bugs will be gone?

-REQUIREMENTS = ['https://github.com/danieljkemp/onkyo-eiscp/archive/'
 -                'python3.zip#onkyo-eiscp==0.9.2']
 +REQUIREMENTS = ['https://github.com/miracle2k/onkyo-eiscp/archive/py3.zip#onkyo-eiscp==1.0']
 +#'python3.zip#onkyo-eiscp==0.9.2']

**Comment by danieljkemp** [comment]
I'm a little confused by all this.

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/media_player/onkyo.py#L17-L19

The latest version of HA is tagged to a recent commit. There is a PR in the works to fix a source selection issue, at which point I'll aim the HA requirement line at the new commit, tagged commit (preferable to tagging a commit) or pypi release (best case).

**Comment by moskovskiy82** [comment]
Ok guess i was a little over my head. Late on i saw that push request contained link to the latest branch. Sorry - not a tech guy. But the files i've found in my ha dir didn't include the fixes for the import statements. So i had to add them manually. If possible if we continue on the HA board? [https://community.home-assistant.io/t/onkyo-broken-in-0-42/15273/2](url)
As currently for me the whole setup is broken and not sure if it's overall or only my problem

**Comment by andrey-git** [comment]
@miracle2k could you release a new pypi version?
There were plenty of changes since Aug 2016.
It would also allow py3 code to depend on a cut pypi version instead of a brunch.
home-assistant/home-assistant#7069

**Comment by miracle2k** [comment]
A new version was pushed to PyPI.
