### ISSUE TITLE
Volume and/or master-volume don't exist for main?

### ISSUE THREAD

**Issue by nelsonmachupa** [miracle2k/onkyo-eiscp#65]
I've installed this amazing utility on 2 separate macs (one being the most updated MPB), as well as ubuntu boxes and the same thing always occurs "('Error:', ValueError('"volume" is not a valid command in zone "main"',))" or "('Error:', ValueError('"master-volume" is not a valid command in zone "main"',))" The volume settings work for the other zones, however. Hope this get's fixed soon! Cheers!

**Comment by drhoet** [comment]
I ran into this issue today too.
Seems to work if you do a raw command with MVL<value>.
If I'm not mistaken, the problem lies in commands.py line 2262: ('master-volume', 'volume'): 'MVL', as neither 'volume' nor 'master-volume' matches this tuple.

**Comment by eidsaa** [comment]
I also have the same issue.

**Comment by miracle2k** [comment]
Sorry about that. Version 1.2.1 should fix it.
