### ISSUE TITLE
Question: Suitable as the basis for Alexa skill?

### ISSUE THREAD

**Issue by whitneyland** [miracle2k/onkyo-eiscp#71]
This project looks like great work.  Is there any reason it make not make a good starting point for developing an Onkyo Alexa skill?

Amazon recently released made it possible to simplify the Alexa user interface for entertainment.  Denon and Sony announced support but not Onkyo.  So I'm trying to see what's available to go around them and just build what is needed for the skill.

**Comment by miracle2k** [comment]
I suppose it does. I don't know about how an Alexa skill is created, but with this library you can send commands, and there is a database with names and text that describes those commands, so that might help to.

**Comment by pll** [comment]
An alexa skill integrating with this would very cool indeed!
