### ISSUE TITLE
High Sierra

### ISSUE THREAD

**Issue by mlamoure** [miracle2k/onkyo-eiscp#78]
Hello,

I'm curious if you've found whether your framework will work in High Sierra?  It was working previously in a plugin I use, and now gets a assertion error when streaming commands.

...eISCP.py", line 198, in parse_header
    assert len(bytes) == 16

I thought that the removal of the tenet binary could be the issue, but restoring it does not seem to resolve the issue.

**Comment by miracle2k** [comment]
There shouldn't be any reason it doesn't work; it's just Python code.
 
We'll need a full stack trace at least to be able to tell more.

**Comment by toshibochan** [comment]
Yep work in hight Sierra

**Comment by mlamoure** [comment]
I forgot to comment back on this, yes it works on HS.  I had a conflict with two software using the same port that caused me to think the EICP code was the problem.

**Comment by jasongabler** [comment]
I am finding this issue tot, though different OS.

```
sh-4.3$ /opt/bin/python3 --version
Python 3.6.2
```

```
Traceback (most recent call last):
  File "volume-normalizer.py", line 14, in <module>
    new_main_vol = receiver.command('main.volume=query')[1]
  File "/opt/lib/python3.6/site-packages/eiscp/core.py", line 480, in command
    response = self.raw(iscp_message)
  File "/opt/lib/python3.6/site-packages/eiscp/core.py", line 464, in raw
    while self.get(False):
  File "/opt/lib/python3.6/site-packages/eiscp/core.py", line 440, in get
    header = eISCPPacket.parse_header(header_bytes)
  File "/opt/lib/python3.6/site-packages/eiscp/core.py", line 101, in parse_header
    assert len(bytes) == 16
AssertionError
```
