### ISSUE TITLE
how to update?

### ISSUE THREAD

**Issue by toshibochan** [miracle2k/onkyo-eiscp#82]
how to update to the new onkyo-eiscp? my version showing onkyo-eiscp 1.0.
I'm trying to use airplay but not command not working.
i did: "onkyo --help-commands zone3 selector" but airplay not on list.

**Comment by toshibochan** [comment]
I was able to update by uninstall and install again. Now in the selection list show Airplay but I was not able to change to airplay.
“onkyo -i 0009B0DD1C16 zone2.selector=airplay”
But come back
“TX-RZ800: selector = N/A”

Please any idea what I doing  wrong?

**Comment by miracle2k** [comment]
Closing this for now. If you still have an issue with the zone selector with the new version, possibly add a ticket for that.

**Comment by toshibochan** [comment]
what is the current version? I'm still having same problem
