### ISSUE TITLE
eISCP on Pioneer VSX-1131 doesn't work

### ISSUE THREAD

**Issue by hebs1** [miracle2k/onkyo-eiscp#87]
Hi,
on my Pioneer AV VSX-1131 (with latest firmware 2099-4040-7080-0008) eISCP doesn't work.
"onkyo --discover" find my device, that works well:
![image](https://user-images.githubusercontent.com/37960314/38165271-3f47650c-3511-11e8-84a6-954e9818d14c.png)
But all commands fail, e.g.:
![image](https://user-images.githubusercontent.com/37960314/38165309-bbcf13b8-3511-11e8-903e-7eefa0bac8dc.png)
Any idea? Thanks a lot!!!

**Comment by HerrRiebmann** [comment]
+1
I try to figure out what´s wrong with the eISCP Protocol, but I didn´t get further.
To be honest, I´m not using the python, but a C# solution.
Messages are being received well and the format seems to be equal to what I send (_after I changed some things, like message-length, end of file-char and encoding_)

**Comment by hebs1** [comment]
Thanks a lot for the hint!!!!

**Comment by glassbase** [comment]
For anyone reading this in the future and has a VSX-1130 like me. Its not the same as the 1131. The 1130 does not have the functionality for this (ISCP).
