### ISSUE TITLE
Volume level mismatch

### ISSUE THREAD

**Issue by tomatpasser** [miracle2k/onkyo-eiscp#89]
Hello, 

I am not able to turn my Pioneer VSX-832 up to more than -42.5 dB with the command line. The command 
`onkyo volume=79` sets it to -42.5 dB, but if I try with 80 it throws an error:

```
onkyo --verbose volume=80
sending to VSX-832: volume=80
Traceback (most recent call last):
  File "/usr/local/bin/onkyo", line 9, in <module>
    load_entry_point('onkyo-eiscp==1.2.4', 'console_scripts', 'onkyo')()
  File "build/bdist.linux-x86_64/egg/eiscp/script.py", line 179, in run
  File "build/bdist.linux-x86_64/egg/eiscp/script.py", line 132, in main
  File "build/bdist.linux-x86_64/egg/eiscp/core.py", line 228, in command_to_iscp
UnboundLocalError: local variable 'value' referenced before assignment
```

I am able to step up the volume to +20 dB, max is 200 in the CLI:
```
onkyo --verbose volume=level-up
sending to VSX-832: volume=level-up
VSX-832: master-volume = 200
```

As I understand it, the newer Pioneer receivers use this Onkyo protocol, but I might be wrong as I have issues. Anyone have insight? 

Thanks

**Comment by miracle2k** [comment]
I vaguely remember this may have been fixed recently. If you didn't do anything special to install the development version, try the new update I just released.

**Comment by tomatpasser** [comment]
Yes, that fixed it, thanks.
