### ISSUE TITLE
No receivers found.

### ISSUE THREAD

**Issue by toshibochan** [miracle2k/onkyo-eiscp#99]
raspberry pi 3+ onkyo-eiscp-1.2.5
i'm sending this CMD:
onkyo --discover:
but not find my receiver.

I try:
onkyo -i 0009B0DD1D28 zone2.power=on
but coming back:
No receivers found.

on other raspberry pi 3 and iMac is working okay. 

please help

**Comment by Tranquility76** [comment]
Same with me - was working on Raspi Model B+ but not working on Raspi 3
(same as #100 ?)
